apiVersion: v1
kind: Service
metadata: 
  name: redis
  app: demo-voting-app
  labels: 
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    - port: 6379
      targetport: 6379
  selector:
    name: redis-pod
    app: demo-voting-app
