apiVersion: v1
kind: Pods
metadata:
  name: result-app-pod
  app: demo-voting-app
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-pod
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80