apiVersion: v1
kind: Pods
metadata:
  name: worker-app-pod
  app: demo-voting-app
spec:
  containers:
    - name: worker-pod
      image: kodekloud/examplevotingapp_worker:v1
      ports:
        - containerPort: 80